server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news_management_service?ApplicationName=TestSweetApp
    username: postgres
    password: 12378
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

cache:
  type: LFU #LRU
  capacity: 8
